### ISSUE TITLE
please provide maven downloads

### ISSUE THREAD

**Issue by binkley** [kilim/kilim#1]
Please upload kilim to a maven repo somewhere.  This makes your library _far_ easier to use!

The minimal artificat is kilim-0.7.2.jar:
(cd classes; jar cvf ../kilim-0.7.2.jar *; jar i ../kilim-0.7.2)

Other nice ones to have include:
kilim-0.7.2-sources.jar
kilim-0.7.2-javadoc.jar
kilim-0.7.2-test-sources.jar
kilim-0.7.2-test-javadoc.jar
kilim-0.7.2-tests.jar

A pom.xml is also helpful:

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
        http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

```
<groupId>kilim</groupId>
<artifactId>kilim</artifactId>
<version>0.7.2</version>

<properties>
    <jdk.version>1.6</jdk.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
</properties>

<dependencies>
    <dependency>
        <groupId>asm</groupId>
        <artifactId>asm-all</artifactId>
        <version>2.2.3</version>
    </dependency>
</dependencies>

<build>
    <plugins>
        <plugin>
            <artifactId>maven-compiler-plugin</artifactId>

            <configuration>
                <source>${jdk.version}</source>
                <target>${jdk.version}</target>
            </configuration>
        </plugin>

        <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>

            <executions>
                <execution>
                    <id>kilim-weave</id>
                    <phase>process-classes</phase>

                    <goals>
                        <goal>java</goal>
                    </goals>
                </execution>
            </executions>

            <configuration>
                <mainClass>kilim.tools.Weaver</mainClass>

                <arguments>
                    <argument>-d</argument>
                    <argument>${project.build.outputDirectory}</argument>
                    <argument>${project.build.outputDirectory}</argument>
                </arguments>
            </configuration>
        </plugin>
    </plugins>
</build>
```

</project>

(That last bit with the exec plugin will automatically weave your compiled code with kilim when building with maven.)

Lastly, here is how I made the javadoc:

mkdir d; javadoc -keywords -linksource -link http://java.sun.com/javase/6/docs/api -author -version -use -d d -source 1.6 -private -sourcepath test -classpath libs/asm-all-2.2.3.jar\;libs/junit.jar\;kilim-0.7.2.jar -subpackages kilim; (cd d; jar cvf ../kilim-0.7.2-test-javadoc.jar *; jar i ../kilim-0.7.2-test-javadoc.jar)

Similarly for src directory.

**Comment by braghome** [comment]
kilim is the such a great secret no one know about it in java world, please add it to maven repositories. For example [learn from this guy how to run popular project](https://github.com/kevinsawicki/http-request): Their are projects that are nothing but wrappers are very very popular just they publish to maven repositories and have excellent java docs. Also add your tests to Travis will ya, it is free for open source projects like these

**Comment by nqzero** [comment]
[kilim 2.0](https://github.com/nqzero/kilim) is available in maven central, currently in pre-release though no major api changes are expected

```
<dependency>
        <groupId>org.db4j</groupId>
        <artifactId>kilim</artifactId>
        <version>2.0.0-15</version>
    </dependency>
```

there's also an included plugin for weaving (or you can use runtime weaving)

full details: https://github.com/nqzero/kilim
