### ISSUE TITLE
@synchronized annotation

### ISSUE THREAD

**Issue by tstockwell** [kilim/kilim#18]
This is just a note to document this idea, I might try to implement this...  

Currently synchronized methods must be rewritten to use the kilim.ReentrantLock.
So this class...

```
class SomeClass {
    synchronized void someMethod() throws Pausable { 
    }
}
```

needs to be rewritten like this...

```
class SomeClass {
    private final kilim.ReentrantLock lock= new kilim.ReentrantLock();
    void someMethod() throws Pausable { 
        lock.lock();
        try {
        }
        finally {
            lock.unlock();
        }
    }
}
```

However, it would be _really_ convenient if kilim weaver would do this automatically.  I imagine an annotation named @synchronized that would replace the synchronized keyword.  Thus, the original method could just be written like this...

```
class SomeClass {
    @synchronized void someMethod() throws Pausable { 
    }
}
```

and the kilim weaver would apply the appropriate changes using kilimReentrantLock.

**Comment by publicocean0** [comment]
the same my problem

**Comment by nqzero** [comment]
five years ago the OP wrote:
> This is just a note to document this idea, I might try to implement this...

afaik, no work was ever done on this proposed enhancement and there's not consensus that if an implementation was provided that the feature would fit into the kilim metaphor. as a result, i'm closing this issue - reopen if needed
