### ISSUE TITLE
Please support ASM 4.0

### ISSUE THREAD

**Issue by andrewdbate** [kilim/kilim#20]
Can you please support ASM 4 in the library in order to support JDK 7?

I know that others, such as Kresten, have forked kilim in order to support ASM 4, but the trouble is that fixes to the main repo are not being merged into these forks and it is all becoming difficult and a bit complicated.

Many thanks :-)

**Comment by nqzero** [comment]
we're currently using asm 5.0.3, so i'm closing this issue as resolved
