### ISSUE TITLE
Ability to provide uncaught exception handler for Scheduler

### ISSUE THREAD

**Issue by aryzhov** [kilim/kilim#31]
There is a piece of code in Task._runExecute() that handles uncaught exceptions:

```
    } catch (Throwable th) {
        th.printStackTrace();
```

Could you please redesign this code to allow supplying an uncaught exception handler to Scheduler. Thanks for this great framework.

**Comment by nqzero** [comment]
recent versions of [kilim 2.0](https://github.com/nqzero/kilim) should allow you to do this

`Scheduler.enableExceptionLog = false` will mute the stack trace, and you can override `schedule(index,task)` to add an exit mailbox (the exception is the value of the exit message)

i'm closing this issue. if you still have a use case that isn't satisfied by these facilities, you can reopen
