### ISSUE TITLE
Missing test classes?

### ISSUE THREAD

**Issue by andrewdbate** [kilim/kilim#32]
Firstly, many thanks for the great work! However, I believe that I have identified a bug in some of the tests.

The test class <tt>kilim.test.TestInvalidPausables</tt> refers to the following classes:

<ul>
<li><tt>kilim.test.ex.ExInvalidConstructor</tt></li>
<li><tt>kilim.test.ex.ExInvalidStaticBlock</tt></li>
<li><tt>kilim.test.ex.ExInvalidCallP_NP</tt></li>
<li><tt>kilim.test.ex.ExInvalidPDerived</tt></li>
<li><tt>kilim.test.ex.ExInvalidPImp</tt></li>
</ul>

However, none of the classes in the above list are in the package <tt>kilim.test.ex</tt>, or any other package for that matter. (I have greped the entire project for the class names.)

The tests that involve these missing classes are in fact passing, but only because the test requires an exception to be thrown, and an exception is indeed thrown, but only due to the class missing, instead of the weaving failing.

Could you confirm that this is a bug? Do you have the source of the missing classes?

**Comment by nqzero** [comment]
@sriram-srinivasan i've added in the missing classes, and mostly they fail as expected. a couple of questions:

* a pausable constructor will weave, but then throws a verify error when it's loaded. i'm assuming that what you intended (based on the comments in this issue) is to throw an exception during weaving. does that seem like either what you remember or if not, then a reasonable approach ?

* i'm not entirely sure what a pausable static block would look like. here's my best guess:

```
class ExInvalidStaticBlock {
    static void foo() throws Pausable {}
    static {
        try { foo(); }
        catch (Exception ex) {}
    }
}
```

any idea what you were imagining when you came up with the static block test ?

**Comment by nqzero** [comment]
@sriram-srinivasan ignore the part about constructors. i found the code for weaving them, and we're clearly intending to throw an exception and there's just a minor bug in the logic which i'll fix

**Comment by nqzero** [comment]
i've added the missing classes for the tests, and the constructor test showed that we would incorrectly weave a pausable constructor, so i fixed that to throw an exception

https://github.com/nqzero/kilim/commit/b2607b4a40477c36f489fad193f5bc83073c85e8

all tests now pass with [kilim 2.0](https://github.com/nqzero/kilim). i'm closing this pending comment from sriram about the static block
