### ISSUE TITLE
Implementation of equals() and merge() in class kilim.analysis.Value (out of date FIXME?)

### ISSUE THREAD

**Issue by andrewdbate** [kilim/kilim#35]
The `equals()` method of kilim.analysis.Value has the following implementation of equals:

``` java
public boolean equals(Object obj) {
    // TODO FIXME : This is WRONG. Two values can be created at the same site when
    // entering a method (all incoming parameter values are given location 0).
    // That would make two distinct params with the same type equal.
    if (this == obj) return true;
    Value other = (Value)obj;
    if (this.typeDesc.equals(other.typeDesc) &&
            this.constVal.equals(other.constVal) &&
                this.numSites == other.numSites) {
        // Check sites
        for (int i = 0; i < this.numSites; i++) {
            if (sites[i] != other.sites[i]) {
                return false;
            }
        }
            return true;
        }
    return false;
}
```

The comment says that the equals implementation is wrong. Is this really the case, or is the comment out of sync with the code?

If the check `this.constVal.equals(other.constVal)` is removed, then I agree with the comment (since then you could not distinguish between two formal parameters with the same type, both of which have have site position zero and the `typeDesc`'s are the same). However, checking the `constVal`'s guards against this, right?

By the same argument, in the the implementation of the method `merge()` in the same class, shouldn't the line

```
if (newNumSites != numSites || newType != typeDesc) { ... }
```

be replaced with:

```
if (newNumSites != numSites || newType != typeDesc || !constVal.equals(other.constVal)) { ... }
```

Right?

Therefore, in summary:
 1) I believe that the FIXME comment in `equals()` should be deleted, since it is out-of-sync with the code.
 2) The implementation of `merge()` may be have bug, since the above check is missing. (Although I expect `merge()` would never be called in this case, it should operate correctly nonetheless.)

Many thanks!

**Comment by nqzero** [comment]
in [kilim 2.0](https://github.com/nqzero/kilim) i removed the offending (incorrect) FIXME and documented the uniqueness requirement: https://github.com/nqzero/kilim/commit/52879966cea181b14f9f6dac6546a376a4602170

closing the issue
