### ISSUE TITLE
Question: What use are the class etc. mirrors for?

### ISSUE THREAD

**Issue by silkentrance** [kilim/kilim#43]
I am trying to figure out why these classes are named Mirror and what their overall use case is. TIA for enlightening me.

**Comment by krestenkrab** [comment]
Mirrors are for use in contexts where you dont want to load the actual classes being woven. In a compiler or a jit for instance.

Sent from my iPad

On 08 May 2015, at 19:52, Carsten Klein <notifications@github.com<mailto:notifications@github.com>> wrote:


I am trying to figure out why these classes are named Mirror and what their overall use case is. TIA for enlightening me.

**Comment by kilim** [comment]
Mirrors provide reflection.  Get it? :) 

java.lang.reflect works for classes in the classpath, but the class files given to the weaver on the command line may or may not be in the classpath. We use asm to reflect on these files. The two use cases are represented by RuntimeClassMirror and CachedClassMirror respectively.

**Comment by silkentrance** [comment]
@kilim thanks for the thorough explanation and that these mirrors are meant for dealing with classes not present on the current classpath.
