### ISSUE TITLE
pass task context when dealing with Java Dynamic Proxy

### ISSUE THREAD

**Issue by JasonHuangHuster** [kilim/kilim#51]
Hi , create a new Task inside Dynamic Proxy invoke method could get  around the non-weaved problem , but if i put the execution logic inside the Task Body, then i will lost the previous Task's context .
`@override
public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {

    final Method mtd = method;
    final Object[] ags = args;
    if (!sppCmdMap.containsKey(method.getName())) {
        return null;
    }
    final RpcContext rpcContext = RpcContext.getContext(KilimTask.getCurrentTask().id);
    Task t = new Task() {
        public void execute() throws Exception, Pausable {

            if (!sppCmdMap.containsKey(mtd.getName())) {
                return;
            }
            RpcCmdInfo cmd = sppCmdMap.get(mtd.getName());
            if (ags[0] instanceof List) {
                List<Message> reqs = (List<Message>) ags[0];
                exit(rpcInvokeBatch(reqs, cmd, rpcContext));
            } else {
                Message req = (Message) ags[0];
                exit(rpcInvoke(req, cmd, rpcContext));
            }
        }
    };
    t.start();
    ExitMsg m = t.joinb();
    return m.result;
}
`

here if i want get the previous Task's Context , i have to use KilimTask.getCurrentTask().id
but this is a Pausable method ...
is there any good idea to solve this ?
Tks advance ! : )
BTW , Kilim is really awesome ! our team is really enjoy with it .

**Comment by JasonHuangHuster** [comment]
how can i get the Id of the outside Task inside the `Task task = new Task(){
// codes
} `

**Comment by nqzero** [comment]
i'm not familiar with the rpc library you're using, nor able to find it with google, so i'm not sure what you're trying to achieve by using the kilim id as a the key for `getContext`. what package is RpcContext in ?

are you calling invoke from inside a Pausable method ?

if so, you can work around the problem by wrapping the method with an inner class

but you're going to run into another problem because you're doing a blocking join with the new task (pausable methods shouldn't block)

**Comment by nqzero** [comment]
i just saw https://github.com/kilim/kilim/issues/50 so i have a better understanding of what you're trying to do

wrap your invoke implementation in an inner class with the rpcContext as a field, and then return the task t and call `t.join()`, ie the pausable variant not the blocking one, from the pausable caller

**Comment by JasonHuangHuster** [comment]
tks for your reply , RpcContext is not part of the problem , but i'll explain the whole process . 

- the RpcContext is a customed context for store parameters which i can i get back when i wanna call rpc method , i preferred this way because i could use them later as `Implicit argument` . it was binded to a Kilim Task Id and i use `ThreadLocal` variables to keep the binding. so everytime i want the parameter related to the CurrentTask , first i need to get the Task Id which is what 'Task.getCurrentTask.id' do .

- these works well if everything goes under common code  block. but now i'm using Java Dynamic Block , which the Proxy's invoke method can't be `Pausable` and i have to put pausable method inside the body of `Task t = new Task(){
callPausableMethod();
}` that means `Task.getCurrentTask.id()` also need to be inside the inner class block(because it is a pausabel method) . it it get the task id inside the inner class then the  task id belongs to the new `Task` i created , not the one i wanted (Outside Task). so the context related to the  previous task is lost . 
- your advice is to wrap my invoke implement in an inner class with a rpcContext as a field. the wrapping  is what i'm doing now , but the problem is i can't get the rpcContext .

**Comment by JasonHuangHuster** [comment]
RpcContext is not a public library , i wrote it myself .

**Comment by nqzero** [comment]
i'm not familiar with java proxies but i just read a little about them. my understanding is that the closure will be serialized, sent to a remote machine and invoked there. if that's the case, just move the RpcContext to a field of the enclosing class. then it will get serialized and sent to the remote machine

>  the problem is i can't get the rpcContext

you can't get it outside of a Task, but just save a reference to one that you get inside a task, and then assign that to a field

if you can reduce your example to a file that will compile, i'll figure out what's going on. if you can't do that, then post a hunk of similar code that works without the proxy, ie if you were going to execute it locally

**Comment by JasonHuangHuster** [comment]
**final long id = Task.getCurrentTask().id);**
Task t = new Task() {
    public void execute() throws Exception, Pausable {
   // codes
    }
};
i've removed the unrelated RpcContext codes cause it's not the related to the problem, 
the bolded line is how i get the context related to the task , i can't get the TaskId by `Task.getCurrentTask().id()` outside the Inner Class of `new Task` because it is pausable , as [https://github.com/kilim/kilim/issues/50](#50) said . 
can i get the parent TaskId inside the `new Task` ?  ie:
`
Task t = new Task() {
    public void execute() throws Exception, Pausable {
    long taskId = this.getParentTaskId();
   // codes
    }
};
`

**Comment by nqzero** [comment]
i don't see a parent task in any of your example code
```
Class Stuff extends Task {
  int parentId;
  public execute() {
    // do parent stuff
    parentId = Task.getCurrentTask.id();
  }
  public invoke() {
    RpcContext context = get(parentId);
    Task t = new Task() { execute {
      rpcInvoke(context);
    }
    t.start();
    ExitMsg m = t.joinb();
    return m.result;
  }
}
```

**Comment by JasonHuangHuster** [comment]
tks a lot for your patient . i can't provide a example file cause it mixed lots of bussiness logic , what's more i think it's better focus on this context or we get confused by unrelated part . 

- any codes that outside the `new Task{}` are executed by another `kilim task` , i call it a parent task because it is in it context we get a new instance of a `new Task {}`.  your code did provided a parent id , but i can't do any `Binding` anymore .

- Java Dynamic Proxy applies `Reflection`  mechanism , the `invoke` method (i pasted the code at the beginning of the issue) is invoke by `Proxy.invoke()` , the  `Proxy` class is a jdk native class , i can't overwrite it . so i could only figure a way out inside this `invoke` method block , to my understanding i can't work around this . 

`
  public Object invoke(Object proxy, Method method, Object[] args) throws Throwable 
  {

        final Method mtd = method;
        final Object[] ags = args;
        // these codes should be running in the routine of a Kilim Task (i call this a parent task, and i 
        //need the id of it),  i can't call Task.getCurrentTask.id() cause it is a Pausable method ,  unless i can get the task id in a NoPausable way .
         Task t = new Task() {
        // this i call it the children task , so how can i get the Task Id of the parent Task, if i call //Task.getCurrentTask.id() here, then i'm getting the id of the current task , not the Parent's 
            public void execute() throws Exception, Pausable {
                Message req = (Message) ags[0];
                exit(rpcInvoke(req, cmd, null));
            }
        };
        t.start();
        ExitMsg m = t.joinb();
        return m.result;
    }

`

**Comment by kilim** [comment]
Let us get back to basics and explore what it is you really want to do. 

Is the following problem statement correct?

“How do I connect to a kilim task on a server from an RMI client”? 

—sriram.

**Comment by JasonHuangHuster** [comment]
hi sriram ,
no ,  there's nothing to do with rpc , my problems is 
"how to get the Task id without throw  a Pausable "

**Comment by kilim** [comment]
In your example, the “parent” invokeO method is not marked pausable. So it is not a kilim Task at all, therefore it does not have a task id. Which is why Seth and I are struggling a bit to understand the notion of parent task, or, the problem at a higher level. 

Separately, have you seen the Task.invoke method()? I am quite sure it doesn’t apply to your case, but still ...  It is mean to invoke a task’s pausable method via reflection.
 
> hi sriram ,
> no , there's nothing to do with rpc , my problems is
> "how to get the Task id without throw a Pausable "
>

**Comment by JasonHuangHuster** [comment]
i got it ...
yeah , i've read kilim Reflection example , but as you known , i'm under the case of Java Dynamic Proxy , the advice sriram gave is to new Task and joinb() to get the result , but this will block the thread . this will downgrade async to sync again . 
do you have any other way to make kilim work with dynamic proxy ? i'm thinking about use cglib to change the bytecodes to apply kilim Reflection invoke .

**Comment by nqzero** [comment]
if you can strip out your business logic and give me an example code that compiles and runs (without kilim) of a `Proxy`, i think i can make it work. replace the `Pausable` (business logic) stuff with a (blocking) `Thread.sleep()`

but i don't have any experience with `Proxy`, so i'm not able to guess at how you're trying to use it based on the snippets you've posted

**Comment by JasonHuangHuster** [comment]
hi nqzero , i'm working on kilim Dynamic weaving now , i downloaded the example under /kilim/test/TestDynamicWeaver.java , and i exchanged the sample file , but it didn't weave at all , and no exception was thrown.
[DynamicWeaverExampleKilim.txt](https://github.com/kilim/kilim/files/1122540/DynamicWeaverExampleKilim.txt)

**Comment by JasonHuangHuster** [comment]
i wrote a simple demo of Dynamic Proxy , which contains four file .
 
- ProxyHandler  in this file is where kilim won't work properly , i've add some comments .

BTW , tons of thanks for your time ... really appreciated 👍

**Comment by nqzero** [comment]
i don't think the dynamic weaver will help you (though it's a great feature and you should check out [my fork, nominally kilim 2.0](https://github.com/nqzero/kilim) which makes some improvements in the runtime weaver)

> i wrote a simple demo of Dynamic Proxy , which contains four file

i don't see any files. best thing is probably to push them to a github repo so we can easily share changes

**Comment by nqzero** [comment]
@JasonHuangHuster i just saw your DynamicWeaverExampleKilim.txt file - i'll take a look and see if that helps me understand this problem

**Comment by nqzero** [comment]
@JasonHuangHuster i reworked the TestDynamicWeaver into a demo along the lines of the example that you posted and added it to [kilim 2.0](https://github.com/nqzero/kilim). here's a direct link:

https://github.com/nqzero/kilim/tree/master/demos/invoke

i also added a new non-pausable method `Task.spawn(Method method,Object obj,Object... args)` that automatically wraps the invocation in a Task and returns it (this is just a convenience, and it's only marginally harder to build the task yourself)

```
        Task.spawn(method,obj).joinb();
```
this will create and start a new task which calls the pausable `obj.method()` using reflection, and blocks until it completes

under the hood this uses `Task.invoke` which in turn uses `Method.invoke`

this is in reply to [your comment above](https://github.com/kilim/kilim/issues/51#issuecomment-312908949)

**Comment by nqzero** [comment]
the invoke demo is working with java 7, 8, 9, 10 and 11 - closing this issue, feel free to reopen or create a new issue if this doesn't solve your issue (no additional comments since january)
