### ISSUE TITLE
Whether count and timerService fields can be changed to protected

### ISSUE THREAD

**Issue by yidongnan** [kilim/kilim#58]
Whether ``count`` and ``timerService`` fields can be changed to protected, so that subclasses can extend the ``AffineThreadPool`` class to override some methods.

https://github.com/kilim/kilim/blob/1b35edb4eb85a44bdeb86bc5358cb7612b92d274/src/kilim/AffineThreadPool.java#L31-L34

**Comment by nqzero** [comment]
that looks ok to me

**Comment by nqzero** [comment]
doesn't appear to hurt performance, so i made most fields and methods protected. probably won't get an new version pushed to maven central today but the code is here:

https://github.com/nqzero/kilim

i've also renamed AffineThreadPool to AffineScheduler (which should have been done before)

i want to rerun all my projects that depend on it first just as a sanity check but very likely that this will be released as is (probably tomorrow)

**Comment by nqzero** [comment]
this is closed by a2483fc

**Comment by nqzero** [comment]
maven central - org.db4j : kilim : 2.0.1
