### ISSUE TITLE
Is this project still be maintained ?

### ISSUE THREAD

**Issue by jalr4ever** [kilim/kilim#75]
Found it no long updated since 2019?

**Comment by nqzero** [comment]
yes, i'm the maintainer and i'm still actively using it. there isn't any active development, but there also aren't any significant pending bugs. with the release of project loom, much of what kilim does is now baked into the jvm, so you may be better off using that

what kilim remains unrivaled at is providing fine-grain control of execution (project loom hides this level of access). there are also some use-cases in which it's faster / more efficient, but that would only be relevant at scale

my most recent work was a major proprietary fork of the weaver, in which it was repurposed for an un-related purpose. i've also considered rebasing the kilim frontend onto loom, but haven't made a decision on that yet

if you have a use-case that's not currently supported, feel free to reach out
